import java.util.Random;
import java.util.Scanner;

public class Task1_numberGame {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        System.out.println("Welcome to the Number Guessing Game.\nYou have to guess the number between 1 - 100 generated by the computer.\n");

        System.out.println("For how many rounds you want to play");
        int rounds = sc.nextInt();
        int count = 1;
        while (count <= rounds) {
            Random rand = new Random();
            int randomNumber = rand.nextInt(100) +1;

            System.out.println("Round " + count+ ", Begins!!!");
            System.out.println("Select the game mode");
            System.out.println("1. Unlimited attempts\n2. Limited attempts\n");

            int modeSelected = sc.nextInt();
            while(modeSelected!=1 && modeSelected!=2){
                System.out.println("Invalid selection. Please choose 1 for unlimited attempts or 2 for limited attempts");
                modeSelected = sc.nextInt();
            }

            int score = 0;

            if (modeSelected == 1) {
                System.out.println("Round " + count+ ", Begins!!!");
                while (true) {
                    System.out.println("Enter your guess: ");
                    int guess = sc.nextInt();
                    score++;

                    if (guess == randomNumber) {
                        System.out.println("Hurray, You won the game!!!!");
                        System.out.println("Your Score is " + score);
                        break;
                    } else if (guess > randomNumber) {
                        System.out.println("Generated number is lower, Try again!");

                    } else {
                        System.out.println("Generated number is higher, Try again!");
                    }
                }
            }

            else if (modeSelected == 2) {
                System.out.println("Round " + count+ ", Begins!!!");
               
                int attempt = 5;
                while (true) {
                    System.out.println("Attempts Remaining: " + attempt);
                    System.out.println("Enter your guess: ");

                    int guess = sc.nextInt();
                    score++;
                    attempt--;
                    if (attempt == 0) {
                        System.out.println("Attempt limit exceeded\nPlease try again ");
                        System.out.println("The correct number is: " + randomNumber);
                        break;
                    }
                    if (guess == randomNumber) {
                        System.out.println("Hurray, You won the game!!!!");
                        System.out.println("Your Score is " + score);
                        break;
                    } else if (guess > randomNumber) {
                        System.out.println("Generated number is lower, Try again!");

                    } else {
                        System.out.println("Generated number is higher, Try again!");
                    }
                }

                }else {
                System.out.println("Invalid input. Please enter valid input.");
                break;
            }
            count++;
        }

    }
}
